### ISSUE TITLE
Auth Token 

### ISSUE THREAD

**Issue by mbraihan** [mdarvanaghi/CSGO-GSI#1]
Sorry, as I am not sure if it is relevant with this repo or not but I was hoping that you could help me on the procedure on how to obtain a auth key as I am stuck with that. 

Thank you

**Comment by Leepee** [comment]
Not the dev but I believe this is informally produced - your gamestate.cfg file and your code have to match is all.

**Comment by Alexico1969** [comment]
This is what I'm getting:

Error response
Error code: 501

Message: Unsupported method ('GET').

Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.
